### ISSUE TITLE
Set up tailwind color configuration

### ISSUE THREAD

**Issue by madshermansen** [NTNU-SmallSat-Lab/outreach-website#108]
### User Story
As a developer, I want to set up a custom color configuration in TailwindCSS so that our application can maintain a consistent and unique color scheme that aligns with our branding guidelines.

### Tasks

- [x] Define the color palette according to the brand guidelines (in figma!).
- [x] Update the `tailwind.config.js` file with the new color settings.
- [x] Test the new color configuration in various components to ensure consistency.
