### ISSUE TITLE
Style project page

### ISSUE THREAD

**Issue by luctra02** [NTNU-SmallSat-Lab/outreach-website#116]
### Goals
Style the cards for each project for a better user experience

### Tasks

- [ ] Change the width and height of the cards
- [ ] Make the whole card clickable
- [ ] Make the card bigger on hover
