### ISSUE TITLE
Install and set up Zustand

### ISSUE THREAD

**Issue by LukasThrane** [NTNU-SmallSat-Lab/outreach-website#152]
### Goals
- Install and set up Zustand

### User Story
As a developer I want to be able to use states across the application in different components

### Tasks
- [ ] npm install Zustand
- [ ] Set up store.ts
- [ ] Add some useful states
