### ISSUE TITLE
Refactor project and satellite

### ISSUE THREAD

**Issue by luctra02** [NTNU-SmallSat-Lab/outreach-website#165]
### Goals
Move parts from code into components to reduce duplicate codes.

### Tasks

- [x] Make a component for related projects/satellites
- [x] Make a component to find the first paragraph for preview on the blogs and project page
- [x] Change coverImage to previewImage for project in Strapi
