### ISSUE TITLE
Fetch satellite data and display on satellites page

### ISSUE THREAD

**Issue by luctra02** [NTNU-SmallSat-Lab/outreach-website#182]
### Goals
Display the correct stats on each satellite on the satellite page

### Tasks

- [ ] Use zustand to fetch satellite data
- [ ] Display the stats in the table for each satellite card
- [ ] Make the whole satellite-card clickable
