### ISSUE TITLE
Recfactor satellite data

### ISSUE THREAD

**Issue by EliasKnudsen** [NTNU-SmallSat-Lab/outreach-website#319]
### Goals
- create new fetch function to fetch using NORADID
- create new zustand states to use ID
- Refactor all files using name to fetch satellite data

### Tasks
Refactor the following files:
- [ ] frontend\src\lib\getSatelliteData.ts
- [ ] frontend\src\lib\store.ts
- [ ] frontend\src\components\satelliteData\SatelliteDataHome.tsx
- [ ] frontend\src\components\satelliteData\SatelliteDataIndividual.tsx
- [ ] frontend\src\components\satelliteData\SatelliteStatsTable.tsx
- [ ] frontend\src\components\satelliteData\SatelliteStatsTableRow.tsx
- [ ] frontend\src\components\homeComponents\homeGlobe.tsx
- [ ] frontend\src\components\homeComponents\SatDropdown.tsx
- [ ] frontend\src\components\homeComponents\SatelliteSelector.tsx
- [ ] frontend\src\components\2dmap\Map2d.tsx
- [ ] frontend\src\components\SatelliteResponsiveTable.tsx
- [ ] frontend\src\app\satellites\page.tsx
- [ ] frontend\src\app\satellites\[satelliteSlug]\page.tsx
