### ISSUE TITLE
Style and Fill in Header/Navbar

### ISSUE THREAD

**Issue by stromseng** [NTNU-SmallSat-Lab/outreach-website#36]
### Goals
Improve the current frontend styling.

### Tasks
- [x] Add the NTNU SmallSatLab Logo
- [x] Fill in the remaining navbar links, and make them functional. Such as blog, people, partners, infrastrucutre etc.
- [x] Change the color to black
- [x] Make the Dark/Light mode a toggle or drowpdown menu, which can include "System" style.
### Connected Issues
