### ISSUE TITLE
Write docs for strapi-adminpanel

### ISSUE THREAD

**Issue by luctra02** [NTNU-SmallSat-Lab/outreach-website#360]
### Goals
Describe how to publish data and what the different fields are.

### Tasks

- [x] Describe different fields like title, slug etc...
- [x] Describe how to use rich text block and how to add video with youtube src
- [x] Describe relations
- [x] Describe the collection- and single types

**Comment by stromseng** [comment]
closed by #364
