### ISSUE TITLE
Create the Blog page and connect to strapi

### ISSUE THREAD

**Issue by stromseng** [NTNU-SmallSat-Lab/outreach-website#38]
### Goals
Show the blog posts from Strapi on a seperate /Blog page.

### Tasks
- [ ] Fetch the data
- [ ] Display the data
- [ ] Style the data
### Connected Issues
#15
