### ISSUE TITLE
Create and style the home page

### ISSUE THREAD

**Issue by stromseng** [NTNU-SmallSat-Lab/outreach-website#43]
### Goals
Setup the initial landing page for the site.

### Tasks

- [x] Create the page
- [ ] Fill in a background image
- [x] Show the large HERO text with the introductory text, and "SmallSatLab" as shown in figma.
- [ ] Showcase example missions.
