### ISSUE TITLE
Figure out tech for map showing satelite location. Setup MVP

### ISSUE THREAD

**Issue by stromseng** [NTNU-SmallSat-Lab/outreach-website#44]
### Tasks

- [ ] Create a component showing a map
- [ ] Show a static location for the satellite.
- [ ] Try and calculate position for the satellite using an API?
- [ ] Show more info on the satellite when clicking on it.
