### ISSUE TITLE
Satelite tracking info site

### ISSUE THREAD

**Issue by EliasKnudsen** [NTNU-SmallSat-Lab/outreach-website#79]
### Goals
Fetch this data from Strapi:
  In orbit
  Launching
  In development
  Rich text for information about the satelite

Fetch from external resource:
Latitude, longtitude, altitude, speed, and more

### Tasks Show this data:

- [ ] Fetching status from strapi
- [ ] Fetching satelite information from strapi
- [ ] Fetching data from external resource like lat, lon, speed, alt and more data
