### ISSUE TITLE
Test navbar

### ISSUE THREAD

**Issue by luctra02** [NTNU-SmallSat-Lab/outreach-website#88]
### Goals
Test if navbar works.

### Tasks

- [ ] Check if navbar is on every page
- [ ] Check if the buttons navigate to the correct pages
- [ ] Test dark/light mode
